name: Mark Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v11
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Issues
          stale-issue-message: |
            Esta issue está inativa há 60 dias e será fechada em 7 dias se não houver atividade.
            Se ainda for relevante, por favor comente para mantê-la aberta.
          close-issue-message: |
            Esta issue foi fechada devido à inatividade. Se ainda for relevante, sinta-se livre para reabri-la.
          days-before-issue-stale: 60
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement'
          
          # Pull Requests
          stale-pr-message: |
            Este PR está inativo há 30 dias e será fechado em 7 dias se não houver atividade.
            Se ainda for relevante, por favor atualize o PR.
          close-pr-message: |
            Este PR foi fechado devido à inatividade. Se ainda for relevante, sinta-se livre para reabri-lo.
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security'
